var json_ifasg_csv_lake_20_use_1 = {
"type": "FeatureCollection",
"name": "ifasg_csv_lake_20_use_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "PID": "PLR029", "LATITUDE": 23.69518, "LONGITUDE": 87.283187, "LOCAL NAME": "JOYALBHANGA OCP FIRST PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "JHANJRA", "LOCATION": "JOYALBHANGA", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B29", "TYPE": 7.0, "LAKE AREA": "15 ha", "WTCL": ">200", "ELEVATION (msl)": "78 m" }, "geometry": { "type": "Point", "coordinates": [ 87.283187, 23.69518 ] } },
{ "type": "Feature", "properties": { "PID": "PLR026", "LATITUDE": 23.713366, "LONGITUDE": 87.26175, "LOCAL NAME": "DALURBANDH OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "PANDABESWAR", "LOCATION": "DALURBANDH", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B26", "TYPE": 7.0, "LAKE AREA": "10.5 ha", "WTCL": ">200", "ELEVATION (msl)": "92 m" }, "geometry": { "type": "Point", "coordinates": [ 87.26175, 23.713366 ] } },
{ "type": "Feature", "properties": { "PID": "PLR024", "LATITUDE": 23.717365, "LONGITUDE": 87.241065, "LOCAL NAME": "BELPAHARI KOTTADIHI OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "PANDABESWAR", "LOCATION": "BELPAHARI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B24", "TYPE": 7.0, "LAKE AREA": "18 ha", "WTCL": ">200", "ELEVATION (msl)": "95 m" }, "geometry": { "type": "Point", "coordinates": [ 87.241065, 23.717365 ] } },
{ "type": "Feature", "properties": { "PID": "PLR021", "LATITUDE": 23.670653, "LONGITUDE": 87.194739, "LOCAL NAME": "CHORA OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "KENDA", "LOCATION": "CHORA", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B21", "TYPE": 7.0, "LAKE AREA": "5.2 ha", "WTCL": ">200", "ELEVATION (msl)": "108 m" }, "geometry": { "type": "Point", "coordinates": [ 87.194739, 23.670653 ] } },
{ "type": "Feature", "properties": { "PID": "PLR008", "LATITUDE": 23.628429, "LONGITUDE": 87.157255, "LOCAL NAME": "DHANDADIHI OCP FIRST PITLAKE ", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "KUNUSTORIA", "LOCATION": "DHANDADIHI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B8", "TYPE": 7.0, "LAKE AREA": "6.5 ha", "WTCL": "<100", "ELEVATION (msl)": "84 m" }, "geometry": { "type": "Point", "coordinates": [ 87.157255, 23.628429 ] } },
{ "type": "Feature", "properties": { "PID": "PLR010", "LATITUDE": 23.633391, "LONGITUDE": 87.161137, "LOCAL NAME": "DHANDADIHI OCP SECOND PITLAKE ", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "KUNUSTORIA", "LOCATION": "DHANDADIHI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B10", "TYPE": 7.0, "LAKE AREA": "6.5 ha", "WTCL": "<100", "ELEVATION (msl)": "87 m" }, "geometry": { "type": "Point", "coordinates": [ 87.161137, 23.633391 ] } },
{ "type": "Feature", "properties": { "PID": "PLR012", "LATITUDE": 23.600001, "LONGITUDE": 87.162428, "LOCAL NAME": "KHADAN KALI OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "KAJORA", "LOCATION": "POLASHBON", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B12", "TYPE": 7.0, "LAKE AREA": "7 ha", "WTCL": "<100", "ELEVATION (msl)": "81 m" }, "geometry": { "type": "Point", "coordinates": [ 87.162428, 23.600001 ] } },
{ "type": "Feature", "properties": { "PID": "PLR030", "LATITUDE": 23.672268, "LONGITUDE": 87.176649, "LOCAL NAME": "KHAS KENDA OCP FIRST PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "KENDA", "LOCATION": "KHAS KENDA", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B30", "TYPE": 7.0, "LAKE AREA": "8.8 ha", "WTCL": ">100", "ELEVATION (msl)": "104 m" }, "geometry": { "type": "Point", "coordinates": [ 87.176649, 23.672268 ] } },
{ "type": "Feature", "properties": { "PID": "PLR004", "LATITUDE": 23.687724, "LONGITUDE": 87.0528, "LOCAL NAME": "PATHALDANGA OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SRIPUR", "LOCATION": "TINPATIA", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B4", "TYPE": 7.0, "LAKE AREA": "5 ha", "WTCL": ">100", "ELEVATION (msl)": "109 m" }, "geometry": { "type": "Point", "coordinates": [ 87.0528, 23.687724 ] } },
{ "type": "Feature", "properties": { "PID": "PLR005", "LATITUDE": 23.609742, "LONGITUDE": 87.065772, "LOCAL NAME": "NIMCHA OCP FIRST PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SATGRAM", "LOCATION": "DAMALI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B5", "TYPE": 7.0, "LAKE AREA": "6 ha", "WTCL": ">100", "ELEVATION (msl)": "83 m" }, "geometry": { "type": "Point", "coordinates": [ 87.065772, 23.609742 ] } },
{ "type": "Feature", "properties": { "PID": "PLR006", "LATITUDE": 23.609254, "LONGITUDE": 87.065145, "LOCAL NAME": "NIMCHA OCP SECOND PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SATGRAM", "LOCATION": "DAMALI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B6", "TYPE": 7.0, "LAKE AREA": "2 ha", "WTCL": "<100", "ELEVATION (msl)": "83 m" }, "geometry": { "type": "Point", "coordinates": [ 87.065145, 23.609254 ] } },
{ "type": "Feature", "properties": { "PID": "PLR059", "LATITUDE": 23.604255, "LONGITUDE": 87.070547, "LOCAL NAME": "NIMCHA OCP FOURTH  PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SATGRAM", "LOCATION": "DAMALI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B46", "TYPE": 7.0, "LAKE AREA": "6.8 ha", "WTCL": ">100", "ELEVATION (msl)": "84 m" }, "geometry": { "type": "Point", "coordinates": [ 87.070547, 23.604255 ] } },
{ "type": "Feature", "properties": { "PID": "PLR035", "LATITUDE": 23.773145, "LONGITUDE": 86.883459, "LOCAL NAME": "DALMIA OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SALANPUR", "LOCATION": "SIKHDASPUR", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B35", "TYPE": 7.0, "LAKE AREA": "15 ha", "WTCL": ">200", "ELEVATION (msl)": "140 m" }, "geometry": { "type": "Point", "coordinates": [ 86.883459, 23.773145 ] } },
{ "type": "Feature", "properties": { "PID": "PLR039", "LATITUDE": 23.785194, "LONGITUDE": 86.924778, "LOCAL NAME": "SHYAMDI OCP FIRST PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SALANPUR", "LOCATION": "SHYAMDI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B39", "TYPE": 7.0, "LAKE AREA": "16.8 ha", "WTCL": ">200", "ELEVATION (msl)": "147 m" }, "geometry": { "type": "Point", "coordinates": [ 86.924778, 23.785194 ] } },
{ "type": "Feature", "properties": { "PID": "PLR052", "LATITUDE": 23.7890472, "LONGITUDE": 86.9576278, "LOCAL NAME": "AMDIHA OCP OITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SALANPUR", "LOCATION": "AMDIHA", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B41", "TYPE": 7.0, "LAKE AREA": "4.5 ha", "WTCL": ">100", "ELEVATION (msl)": "140 m" }, "geometry": { "type": "Point", "coordinates": [ 86.9576278, 23.7890472 ] } },
{ "type": "Feature", "properties": { "PID": "PLR001", "LATITUDE": 23.814794, "LONGITUDE": 86.997859, "LOCAL NAME": "KATAPAHARI OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SRIPUR", "LOCATION": "KATAPAHARI", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B1", "TYPE": 7.0, "LAKE AREA": "8 ha", "WTCL": ">100", "ELEVATION (msl)": "130 m" }, "geometry": { "type": "Point", "coordinates": [ 86.997859, 23.814794 ] } },
{ "type": "Feature", "properties": { "PID": "PLR034", "LATITUDE": 23.759945, "LONGITUDE": 86.866493, "LOCAL NAME": "BAMNA OCP PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "SODEPUR", "LOCATION": "BORIRA", "STATE": "WEST BENGAL", "DISTRICT": "PASCHIM BARDHAMAN", "DLID": "B34", "TYPE": 7.0, "LAKE AREA": "2.8 ha", "WTCL": ">100", "ELEVATION (msl)": "130 m" }, "geometry": { "type": "Point", "coordinates": [ 86.866493, 23.759945 ] } },
{ "type": "Feature", "properties": { "PID": "PLR043", "LATITUDE": 23.797147, "LONGITUDE": 86.696175, "LOCAL NAME": "MUGMA OCP THIRD PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "MUGMA", "LOCATION": "NIRSA", "STATE": "JHARKHAND", "DISTRICT": "DHANBAD", "DLID": "D3", "TYPE": 7.0, "LAKE AREA": "4.2 ha", "WTCL": ">100", "ELEVATION (msl)": "138 m" }, "geometry": { "type": "Point", "coordinates": [ 86.696175, 23.797147 ] } },
{ "type": "Feature", "properties": { "PID": "PLR044", "LATITUDE": 23.780128, "LONGITUDE": 86.703036, "LOCAL NAME": "MUGMA OCP FOURTH PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "MUGMA", "LOCATION": "NIRSA", "STATE": "JHARKHAND", "DISTRICT": "DHANBAD", "DLID": "D4", "TYPE": 7.0, "LAKE AREA": "14 ha", "WTCL": ">100", "ELEVATION (msl)": "139 m" }, "geometry": { "type": "Point", "coordinates": [ 86.703036, 23.780128 ] } },
{ "type": "Feature", "properties": { "PID": "PLR048", "LATITUDE": 23.755367, "LONGITUDE": 86.774697, "LOCAL NAME": "MUGMA OCP EIGHTH PITLAKE", "OWNER": "EASTERN COALFIELDS LIMITED", "AREA": "MUGMA", "LOCATION": "SIULIBAN", "STATE": "JHARKHAND", "DISTRICT": "DHANBAD", "DLID": "D8", "TYPE": 7.0, "LAKE AREA": "3.5 ha", "WTCL": ">100", "ELEVATION (msl)": "134 m" }, "geometry": { "type": "Point", "coordinates": [ 86.774697, 23.755367 ] } }
]
}
